#!/usr/bin/env bash

# enable it
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# copy default config
if [[ ! -f /home/dokku/haproxy/_00_default.cfg ]]; then
  sudo cp /etc/haproxy/haproxy.cfg /home/dokku/haproxy/_00_default.cfg
fi

# set new haproxy config location
sudo sed -i 's/CONFIG=\/etc\/haproxy\/haproxy.cfg/CONFIG=\/home\/dokku\/haproxy\/haproxy.cfg/g' /etc/init.d/haproxy

# enable stats
cat<<EOF > /home/dokku/haproxy/_11_stats.cfg
listen stats :9090
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    stats auth admin:admin
EOF

# concatenate configs
cat /home/dokku/haproxy/_* > /home/dokku/haproxy/haproxy.cfg

# restart service
sudo service haproxy restart
