#!/usr/bin/env bash

# enable it
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# give access
sudo cat<<EOF > /etc/sudoers.d/dokku-haproxy
  %dokku ALL=(ALL) NOPASSWD:/etc/init.d/haproxy *
EOF

# create directory
mkdir -p /var/lib/dokku-haproxy

# create default config
cat <<EOF > /var/lib/dokku-haproxy/_00_default.cfg
global
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  daemon

EOF

# set new haproxy config location
sudo sed -i 's/CONFIG=\/etc\/haproxy\/haproxy.cfg/CONFIG=\/home\/dokku\/haproxy\/haproxy.cfg/g' /etc/init.d/haproxy

# enable stats
cat<<EOF > /var/lib/dokku-haproxy/_11_stats.cfg
listen stats :9090
  mode http
  timeout connect 5s
  timeout client 24h
  timeout server 24h
  stats enable
  stats hide-version
  stats realm Haproxy\ Statistics
  stats uri /
  stats auth admin:admin

EOF

# concatenate configs
cat /var/lib/dokku-haproxy/_* > /var/lib/dokku-haproxy/haproxy.cfg

# give access
chown dokku:dokku /var/lib/dokku-haproxy
chown dokku:dokku /var/lib/dokku-haproxy/*

# restart service
sudo service haproxy restart
