#!/usr/bin/env bash

APP="$1"

# remove config file
rm /home/dokku/haproxy/_22_$APP.cfg

# concatenate configs
cat /home/dokku/haproxy/_* > /home/dokku/haproxy/haproxy.cfg

# reload config
sudo /etc/init.d/haproxy reload
