#!/usr/bin/env bash

APP="$1"

# create config
/var/lib/dokku/plugins/dokku-haproxy/create-config $APP

# concatenate configs
cat /home/dokku/haproxy/_* > /home/dokku/haproxy/haproxy.cfg

# reload config
sudo /etc/init.d/haproxy reload
