#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# get app
APP="$1"

# check if there is a PORTS file
if [ -f $DOKKU_ROOT/$APP/PORTS ]; then
  # log
  echo "-----> Removing haproxy configuration"

  # remove config file
  rm -f /var/lib/dokku-haproxy/_22_$APP.cfg

  # concatenate configs
  cat /var/lib/dokku-haproxy/_* > /var/lib/dokku-haproxy/haproxy.cfg

  # reload config
  sudo /etc/init.d/haproxy restart
fi
