#!/usr/bin/env bash

# export need variables
export APP=$APP
export DOKKU_ROOT=$DOKKU_ROOT

# create config
/var/lib/dokku/plugins/dokku-haproxy/create-config

# concatenate configs
cat /home/dokku/haproxy/_* > /home/dokku/haproxy/haproxy.cfg

# reload config
sudo /etc/init.d/haproxy reload
